import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Mail from "./_components/Mail";
import Social from "./_components/Social";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yash Ghugardare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-bgColor`}>
        <Header />
        {children}
        <Mail />
        <Social />
      </body>
    </html>
  );
}
